name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8.12'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: upgrade pip to avoid the AttributeError
      run: |
          python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        pip install opencv-python numpy==1.23.0 onnx_simplifier==0.3.10 onnxruntime==1.16.0 pathlib argparse
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 --count --select=E9,F63,F7,F82 --show-source --statistics ./detect.py
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics ./detect.py
    - name: Test with pytest
      run: |
        conda install pytest
        pytest ./detect.py
